export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_FILTERED_PRODUCTS: "FETCH_FILTERED_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
